# Generated by Django 2.1.3 on 2018-12-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hotcost',
            new_name='oldcost',
        ),
    ]
