# Generated by Django 2.1.3 on 2018-12-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_hotdial_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdial',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
