# Generated by Django 2.1.3 on 2018-12-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_hotdial_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Three_slide_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=250)),
                ('title2', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Three_slide_news_images', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
    ]
