# Generated by Django 2.1.3 on 2018-12-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181207_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar_images/default.png', null=True, upload_to='avatar_images', verbose_name='Аватар'),
        ),
    ]
