# Generated by Django 2.1.3 on 2019-01-11 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190111_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 13, 2, 48, 866176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True, verbose_name='Возраст'),
        ),
    ]
