# Generated by Django 2.1.3 on 2019-01-14 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190114_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='language',
            field=models.TextField(blank=True, max_length=10, verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='url',
            field=models.TextField(blank=True, max_length=512, verbose_name='url на google+'),
        ),
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 12, 47, 19, 397076, tzinfo=utc)),
        ),
    ]
