# Generated by Django 2.1.3 on 2019-01-15 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190114_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 7, 25, 5, 639707, tzinfo=utc)),
        ),
    ]
