# Generated by Django 2.1.3 on 2018-12-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_cart_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_cost',
        ),
    ]
